# Generated by Django 3.2.20 on 2023-07-18 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitemtemplate',
            name='text',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='userchecklist',
            name='created_from',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='userchecklist',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='userchecklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userchecklistitem',
            name='text',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='userchecklistitem',
            name='user_checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.userchecklist'),
        ),
        migrations.AlterField(
            model_name='userchecklistitemtemplate',
            name='text',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='userchecklisttemplate',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
