# Generated by Django 3.2.6 on 2021-08-27 03:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0002_auto_20210826_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('04cd01a4-94ad-4334-956f-9baf59773243'), primary_key=True, serialize=False),
        ),
    ]
