# Generated by Django 3.2.6 on 2021-08-27 03:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0003_alter_responsemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ded00b86-fe3b-48ac-ab28-d0774cf8dd45'), primary_key=True, serialize=False),
        ),
    ]
