# Generated by Django 3.2.6 on 2021-08-27 23:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0004_alter_responsemodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsemodel',
            name='text_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c7506fa0-2eb3-4e53-9412-f449a87b06d8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='response',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3)], max_length=1),
        ),
    ]
