# Generated by Django 3.2.6 on 2021-08-28 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('text_app', '0005_auto_20210827_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoneNumber',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phone_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(choices=[(True, True), (False, False)], default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e070fe0e-82d1-44b4-9875-169b6d166a1a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='mood_response',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
        migrations.CreateModel(
            name='ActiveSurveyStore',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7f86ef2c-2044-4e5f-a6e1-51aaa97e05c6'), primary_key=True, serialize=False)),
                ('active_survey_id', models.UUIDField(default=uuid.UUID('4621b0f2-e265-4bf0-b108-b2a642cfde1f'))),
                ('survey_expire_datetime', models.DateTimeField()),
                ('expired', models.BooleanField(choices=[(True, True), (False, False)], default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
