# Generated by Django 3.2.6 on 2021-08-28 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0008_alter_activesurveystore_active_survey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesurveystore',
            name='active_survey_id',
            field=models.UUIDField(default=uuid.UUID('037600b3-d5e1-4a96-b097-f32fcdac239f'), primary_key=True, serialize=False),
        ),
    ]
