# Generated by Django 3.2.6 on 2021-08-28 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0009_alter_activesurveystore_active_survey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesurveystore',
            name='active_survey_id',
            field=models.UUIDField(default=uuid.UUID('48405a9f-4dd9-47fe-9deb-fbe72ecf4c66'), primary_key=True, serialize=False),
        ),
    ]
