# Generated by Django 3.2.6 on 2021-08-28 07:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0010_alter_activesurveystore_active_survey_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activesurveystore',
            old_name='expired',
            new_name='expired_or_completed',
        ),
        migrations.AlterField(
            model_name='activesurveystore',
            name='active_survey_id',
            field=models.UUIDField(default=uuid.UUID('c6e28cdf-721b-409b-a044-7c693f95123e'), primary_key=True, serialize=False),
        ),
    ]
