# Generated by Django 3.2.6 on 2021-08-28 07:56

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0011_auto_20210828_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphonenumber',
            name='expire_after_hours',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='userphonenumber',
            name='send_survey_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activesurveystore',
            name='active_survey_id',
            field=models.UUIDField(default=uuid.UUID('c3d79f97-5caa-4b8d-a0a6-cd2e3fc639a3'), primary_key=True, serialize=False),
        ),
    ]
