# Generated by Django 3.2.6 on 2021-08-28 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0012_auto_20210828_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesurveystore',
            name='completed',
            field=models.BooleanField(choices=[(True, True), (False, False)], default=False),
        ),
        migrations.AddField(
            model_name='activesurveystore',
            name='expired',
            field=models.BooleanField(choices=[(True, True), (False, False)], default=False),
        ),
        migrations.AlterField(
            model_name='activesurveystore',
            name='active_survey_id',
            field=models.UUIDField(default=uuid.UUID('02f4c0d0-0446-4261-9e4a-e062018e9ef3'), primary_key=True, serialize=False),
        ),
    ]
