# Generated by Django 3.2.6 on 2021-08-28 17:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0013_auto_20210828_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesurveystore',
            name='active_survey_id',
            field=models.UUIDField(default=uuid.UUID('58f37cba-24a9-49d1-b058-6a0d91642c85'), primary_key=True, serialize=False),
        ),
    ]
