# Generated by Django 3.2.6 on 2021-08-29 03:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0015_alter_activesurveystore_active_survey_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesurveystore',
            name='sent',
            field=models.BooleanField(choices=[(True, True), (False, False)], default=False),
        ),
        migrations.AlterField(
            model_name='activesurveystore',
            name='active_survey_id',
            field=models.UUIDField(default=uuid.UUID('2c34b994-1d83-4764-b9d6-d83da3c53629'), primary_key=True, serialize=False),
        ),
    ]
