# Generated by Django 3.2.6 on 2021-08-29 05:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0016_auto_20210828_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphonenumber',
            name='last_survey_sent_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userphonenumber',
            name='next_survey_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userphonenumber',
            name='survey_interval_hours',
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='activesurveystore',
            name='active_survey_id',
            field=models.UUIDField(default=uuid.UUID('840ae819-cf7c-4aac-aa12-3e90af40dc31'), primary_key=True, serialize=False),
        ),
    ]
