# Generated by Django 3.2.6 on 2021-08-29 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0017_auto_20210829_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesurveystore',
            name='active_survey_id',
            field=models.UUIDField(default=uuid.UUID('d63cc3d6-bad9-4107-b56d-859aac815504'), primary_key=True, serialize=False),
        ),
    ]
