# Generated by Django 3.2.6 on 2021-08-29 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0018_alter_activesurveystore_active_survey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesurveystore',
            name='active_survey_id',
            field=models.UUIDField(default=uuid.UUID('71ce213c-15c6-448f-986b-a46f43f49422'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='last_survey_sent_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='next_survey_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
