# Generated by Django 3.2.6 on 2021-08-29 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0019_auto_20210829_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesurveystore',
            name='active_survey_id',
            field=models.UUIDField(default=uuid.UUID('87d971ef-8391-4438-93a3-1718c184861c'), primary_key=True, serialize=False),
        ),
    ]
