# Generated by Django 3.2.6 on 2021-08-29 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0020_alter_activesurveystore_active_survey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesurveystore',
            name='active_survey_id',
            field=models.UUIDField(default=uuid.UUID('58a88fbe-ead8-40ea-89a5-44802eaa4b41'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='next_survey_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 15, 47, 58, 771581, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
