# Generated by Django 3.2.6 on 2021-08-31 01:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0021_auto_20210829_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySymptoms',
            fields=[
                ('symptom', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='daily_weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='hours_slept',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='activesurveystore',
            name='active_survey_id',
            field=models.UUIDField(default=uuid.UUID('e0d18766-07a0-4145-89b0-aa9b71bdb6b2'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='response',
            field=models.SmallIntegerField(choices=[(-4, -4), (-3, -3), (-2, -2), (-1, -1), (1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='daily_symptoms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='text_app.dailysymptoms'),
        ),
    ]
