# Generated by Django 3.2.6 on 2021-09-04 04:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0023_auto_20210830_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesurveystore',
            name='active_survey_id',
            field=models.UUIDField(default=uuid.UUID('72108acd-8651-418e-989a-12d0bf151754'), primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='responsemodel',
            name='daily_symptoms',
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='daily_symptoms',
            field=models.ManyToManyField(to='text_app.DailySymptoms'),
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='mood_response',
            field=models.SmallIntegerField(choices=[(-4, -4), (-3, -3), (-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
