# Generated by Django 3.2.6 on 2021-09-04 04:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0024_auto_20210904_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesurveystore',
            name='active_survey_id',
            field=models.UUIDField(default=uuid.UUID('f47b2896-a0b7-4d91-9bf1-3497861281ac'), primary_key=True, serialize=False),
        ),
    ]
