# Generated by Django 3.2.6 on 2021-09-04 04:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0025_alter_activesurveystore_active_survey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesurveystore',
            name='active_survey_id',
            field=models.UUIDField(default=uuid.UUID('a46f1c70-177f-439e-9c1d-8dd31b033b6f'), primary_key=True, serialize=False),
        ),
    ]
