# Generated by Django 3.2.6 on 2021-09-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0028_alter_activesurveystore_active_survey_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsemodel',
            old_name='datetime',
            new_name='created_datetime',
        ),
    ]
