# Generated by Django 3.2.6 on 2021-09-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0029_rename_datetime_responsemodel_created_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsemodel',
            name='modified_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
