# Generated by Django 3.2.6 on 2021-09-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0030_responsemodel_modified_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activesurveystore',
            name='expired_or_completed',
        ),
        migrations.AddField(
            model_name='activesurveystore',
            name='sent_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
