# Generated by Django 3.2.6 on 2021-09-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0031_auto_20210906_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemodel',
            name='daily_symptoms',
            field=models.ManyToManyField(blank=True, to='text_app.DailySymptoms'),
        ),
    ]
