# Generated by Django 3.2.6 on 2021-09-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0032_alter_responsemodel_daily_symptoms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activesurveystore',
            options={'ordering': ['sent_datetime']},
        ),
    ]
