# Generated by Django 3.2.6 on 2021-09-14 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0034_alter_responsemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activesurveystore',
            options={'ordering': ['-sent_datetime']},
        ),
        migrations.AlterModelOptions(
            name='responsemodel',
            options={'ordering': ['-created_datetime']},
        ),
    ]
