# Generated by Django 3.2.6 on 2021-09-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0035_auto_20210913_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activesurveystore',
            options={'ordering': ['-created_datetime']},
        ),
        migrations.AddField(
            model_name='activesurveystore',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
